### ISSUE TITLE
About LuaSQL-ODBC-SQLite3

### ISSUE THREAD

**Issue by jhernancanom** [keplerproject/luasql#50] opened 2016-06-30 20:18 UTC
Hello, friends.

This message is about LuaSQL, specifically ODBC connection.

I am trying to use SQLite with the Lua language. I found a DLL (not LuaSQL) and I try it. But I discover that it only runs with Lua v5.1.

I want to use the last version of the Lua language (I am trying v5.3.2, but I see today that v5.3.3 has come). And also I want to use it with the last version of SQLite.

My new scenario is: I want to use Lua with SQLite through LuaSQL. But I need to understand something....

I have found that every Lua utility that I want to "use" needs to be "compiled" from C-sources (or C++, or any...).
And also LuaSQL-SQLite3 (please consider from now to on, that I am not interested in using SQLite v2) seems to need to be compiled.

I conclude this because I have not found any DLL in the GitHub download (of LuaSQL or any other tool).

Next I am going to say this lecture about a possible scenario in my environment and I want you correct me where necesary.

If I compile LuaSQL-SQLite3 it only will run in the exact version of Lua with it be compiled and with the exact version of SQLite  with it be compiled.
If I would want change Lua (.EXE and .DLL) for another higher version, LuaSQL-SQLite3 will not run.
If I would want change SQLite (.DLL) for another higher version, LuaSQL-SQLite3 will not run.
((Please say yes or no to this comment))

Then I turn my mind to **LuaSQL-ODBC**.
I (Hernan Cano) consider that if I change SQLite for a higher version, I still could use LuaSQL-SQLite3 (say "LuaSQL-ODBC-SQLite3 do will run") because the ODBC.DLL in LuaSQL is the same and the string connection that I use for connecting is the same.

Please: I need an environment where I could change the version of Lua (I understand that the Lua.EXE and the Lua.DLL must be the same version) without needing to change SQLite.

And: I need the same environment where I could change the version of SQLite without needing to change Lua.

For what I understand, I could not do that if I would use LuaSQL-SQLite, but I think I have BETTER probabilities if I use LuaSQL-ODBC (I say BETTER, not the maximum).
((Please say something to this comment))

If with LuaSQL-ODBC my probabilities could be better, I would prefer to download the DLL or all the binaries from respective URLs; but also I will accept to have to compile the binaries (why all these Lua tools do not come in DLL? I do not see a reason for this).

Clarify me these doubts of mine.

Thanks, friends.

**HERNAN CANO M**
Systems Analyst - Programmer

**Comment by blumf** [comment] 2016-07-01 13:21
I'll close this as a duplicate of #52

**Closed by blumf** 2016-07-01 13:21 UTC

**Comment by jhernancanom** [comment] 2016-07-01 19:06
Sorry, friend.

I put these messages and the questions are different: in [#50] I pretend
ask for a problem, and in [#52] I want to be consider a tester of
LuaSQL-ODBC and LuaSQL-SQLite3.

But no problem: I'll go on with this info.

Thanks an way.



2016-07-01 8:21 GMT-05:00 blumf:
